services:
  ubuntu:
    container_name: workstation_${PROJECT_NAME}
    image: mcr.microsoft.com/devcontainers/base:ubuntu-${UBUNTU_VERSION}
    ports:
      - "${HTTP_PORT}:8000"
      - "${VITE_PORT}:5173"
    restart: "unless-stopped"
    tty: true
    stop_signal: SIGTERM
    volumes:
      - ./:/${CONTAINER_WORKSPACE_FOLDER}
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials
    networks:
      - moztopia_network

  redis:
    container_name: redis_${PROJECT_NAME}
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - /${PROJECT_NAME}/.devcontainer/redis/data:/data:rw
      - /${PROJECT_NAME}/.devcontainer/redis/log:/var/log/redis:rw
    networks:
      - moztopia_network

  mariadb:
    container_name: mariadb_${PROJECT_NAME}
    image: mariadb:${MARIADB_VERSION}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - /${PROJECT_NAME}/.devcontainer/mariadb/data:/var/lib/mysql:rw
      - /${PROJECT_NAME}/.devcontainer/mariadb/log:/var/log/mysql:rw
    environment:
      - MYSQL_DATABASE=${PROJECT_NAME}
      - MYSQL_USER=${PROJECT_NAME}_user
      - MYSQL_PASSWORD=${PROJECT_NAME}_secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - moztopia_network

networks:
  moztopia_network:
    name: moztopia_network
    driver: bridge
