services:
  ubuntu:
    container_name: workstation_${COMPOSE_PROJECT_NAME}
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    ports:
      - "${HTTP_PORT}:8000"
      - "${VITE_PORT}:5173"
    restart: "unless-stopped"
    tty: true
    stop_signal: SIGTERM
    volumes:
      - ./:/devlite
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials

  redis:
    container_name: redis_${COMPOSE_PROJECT_NAME}
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${CONTAINERS_CONFIGDIR}/redis/data:/data:rw
      - ${CONTAINERS_CONFIGDIR}/redis/log:/var/log/redis:rw

  mariadb:
    container_name: mariadb_${COMPOSE_PROJECT_NAME}
    image: mariadb:11.7
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${CONTAINERS_CONFIGDIR}/mariadb/data:/var/lib/mysql:rw
      - ${CONTAINERS_CONFIGDIR}/mariadb/log:/var/log/mysql:rw
    environment:
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
      - MYSQL_USER=${COMPOSE_PROJECT_NAME}_user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
