services:
  ubuntu:
    container_name: workstation_${COMPOSE_PROJECT_NAME}
    build:
      dockerfile: ${CONTAINERS_CONFIGDIR}/workstation/workstation.Dockerfile
    restart: "unless-stopped"
    stop_signal: SIGTERM
    volumes:
      - ./:/workspace
    env_file:
      - path: .env
      - path: ${CONTAINERS_CONFIGDIR}/workstation/docker-compose-workstation.env

  nginx:
    container_name: nginx_${COMPOSE_PROJECT_NAME}
    build:
      dockerfile: ${CONTAINERS_CONFIGDIR}/nginx/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${APP_WEBROOT}:/usr/share/nginx/html:rw
      - ./${CONTAINERS_CONFIGDIR}/nginx/templates:/etc/nginx/templates:rw
      - ./${CONTAINERS_CONFIGDIR}/nginx/log:/var/log/nginx:rw
      - ./${CONTAINERS_CONFIGDIR}/nginx/ssl:/etc/nginx/ssl:ro
    env_file:
      - path: .env
      - path: ${CONTAINERS_CONFIGDIR}/nginx/docker-compose-nginx.env

  php:
    container_name: php_${COMPOSE_PROJECT_NAME}
    build:
      dockerfile: ${CONTAINERS_CONFIGDIR}/php/php.Dockerfile
    volumes:
      - ./${APP_WEBROOT}:/var/www/html:rw
      - ./${DEVSTATION_ROOT}:/var/www/html_devstation_app:rw
    env_file:
      - path: .env
      - path: ${CONTAINERS_CONFIGDIR}/php/docker-compose-php.env
      
  redis:
    container_name: redis_${COMPOSE_PROJECT_NAME}
    image: redis:latest
    volumes:
      - ./${CONTAINERS_CONFIGDIR}/redis/data:/data:rw
    env_file:
      - path: .env
      - path: ${CONTAINERS_CONFIGDIR}/redis/docker-compose-redis.env

  mariadb:
    container_name: mariadb_${COMPOSE_PROJECT_NAME}
    build:
      dockerfile: ${CONTAINERS_CONFIGDIR}/mariadb/mariadb.Dockerfile
    volumes:
      - ./${CONTAINERS_CONFIGDIR}/mariadb/data:/var/lib/mysql:rw
    env_file:
      - path: .env
      - path: ${CONTAINERS_CONFIGDIR}/mariadb/docker-compose-mariadb.env
